apiVersion: v1
kind: Service
metadata:
  name:  mysql-headless
  namespace: expense
spec:
  clusterIP: None
  selector: 
    name: mysql
    tier: db
    project: expense
    
  ports: 
    - name: mysql-service-port
      protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name:  mysql
  namespace: expense
spec:
  selector: 
    name: mysql
    tier: db
    project: expense
    
  ports: 
    - name: mysql-service-port
      protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      name: mysql
      tier: db
      project: expense
  serviceName: mysql-headless
  template:
    metadata:
      labels:  
        name: mysql
        tier: db
        project: expense
    spec:
      securityContext:
        fsGroup: 999
      containers: 
      - name: mysql
        image: vamsidocker012/mysql:{{ .Values.deployment.imageVersion }}
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce"]
      storageClassName: expense-ebs
      resources: 
        requests:
          storage: 1Gi

---



    
      

