apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    name: backend
    tier: app
    project: expense  
spec:
  replicas: 2
  selector:
    matchLabels:
      name: backend
      tier: app
      project: expense
  template:
    metadata:
      labels:
        name: backend
        tier: app
        project: expense 
    spec:
      containers:
      - name: backend-expense
        image: vamsidocker012/backend:v1 
        envFrom:
        - configMapRef:
            name: backend
    
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
  labels:  
    name: backend
    tier: app
    project: expense
spec:
  selector:
      name: backend
      tier: app
      project: expense
  ports:
    - name: backend-ports
      protocol: TCP
      port: 8080
      targetPort: 8080



    
      

